/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scribe_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace opencensus {
namespace scribe {

int _kResultCodeValues[] = {ResultCode::OK, ResultCode::TRY_LATER};
const char* _kResultCodeNames[] = {"OK", "TRY_LATER"};
const std::map<int, const char*> _ResultCode_VALUES_TO_NAMES(
    ::apache::thrift::TEnumIterator(2, _kResultCodeValues, _kResultCodeNames),
    ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const ResultCode::type& val) {
  std::map<int, const char*>::const_iterator it =
      _ResultCode_VALUES_TO_NAMES.find(val);
  if (it != _ResultCode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

LogEntry::~LogEntry() throw() {}

void LogEntry::__set_category(const std::string& val) { this->category = val; }

void LogEntry::__set_message(const std::string& val) { this->message = val; }
std::ostream& operator<<(std::ostream& out, const LogEntry& obj) {
  obj.printTo(out);
  return out;
}

uint32_t LogEntry::read(::apache::thrift::protocol::TProtocol* iprot) {
  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  while (true) {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid) {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->category);
          this->__isset.category = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          this->__isset.message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LogEntry::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LogEntry");

  xfer += oprot->writeFieldBegin("category",
                                 ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->category);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("message",
                                 ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LogEntry& a, LogEntry& b) {
  using ::std::swap;
  swap(a.category, b.category);
  swap(a.message, b.message);
  swap(a.__isset, b.__isset);
}

LogEntry::LogEntry(const LogEntry& other0) {
  category = other0.category;
  message = other0.message;
  __isset = other0.__isset;
}
LogEntry& LogEntry::operator=(const LogEntry& other1) {
  category = other1.category;
  message = other1.message;
  __isset = other1.__isset;
  return *this;
}
void LogEntry::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LogEntry(";
  out << "category=" << to_string(category);
  out << ", "
      << "message=" << to_string(message);
  out << ")";
}

}  // namespace scribe
}  // namespace opencensus
