/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "zipkin_core_constants.h"

namespace opencensus {
namespace zipkin {

const zipkin_coreConstants g_zipkin_core_constants;

zipkin_coreConstants::zipkin_coreConstants() {
  CLIENT_SEND = "cs";

  CLIENT_RECV = "cr";

  SERVER_SEND = "ss";

  SERVER_RECV = "sr";

  WIRE_SEND = "ws";

  WIRE_RECV = "wr";

  CLIENT_SEND_FRAGMENT = "csf";

  CLIENT_RECV_FRAGMENT = "crf";

  SERVER_SEND_FRAGMENT = "ssf";

  SERVER_RECV_FRAGMENT = "srf";

  HTTP_HOST = "http.host";

  HTTP_METHOD = "http.method";

  HTTP_PATH = "http.path";

  HTTP_URL = "http.url";

  HTTP_STATUS_CODE = "http.status_code";

  HTTP_REQUEST_SIZE = "http.request.size";

  HTTP_RESPONSE_SIZE = "http.response.size";

  LOCAL_COMPONENT = "lc";

  ERROR = "error";

  CLIENT_ADDR = "ca";

  SERVER_ADDR = "sa";
}

}  // namespace zipkin
}  // namespace opencensus
