/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zipkin_core_CONSTANTS_H
#define zipkin_core_CONSTANTS_H

#include "zipkin_core_types.h"

namespace opencensus {
namespace zipkin {

class zipkin_coreConstants {
 public:
  zipkin_coreConstants();

  std::string CLIENT_SEND;
  std::string CLIENT_RECV;
  std::string SERVER_SEND;
  std::string SERVER_RECV;
  std::string WIRE_SEND;
  std::string WIRE_RECV;
  std::string CLIENT_SEND_FRAGMENT;
  std::string CLIENT_RECV_FRAGMENT;
  std::string SERVER_SEND_FRAGMENT;
  std::string SERVER_RECV_FRAGMENT;
  std::string HTTP_HOST;
  std::string HTTP_METHOD;
  std::string HTTP_PATH;
  std::string HTTP_URL;
  std::string HTTP_STATUS_CODE;
  std::string HTTP_REQUEST_SIZE;
  std::string HTTP_RESPONSE_SIZE;
  std::string LOCAL_COMPONENT;
  std::string ERROR;
  std::string CLIENT_ADDR;
  std::string SERVER_ADDR;
};

extern const zipkin_coreConstants g_zipkin_core_constants;

}  // namespace zipkin
}  // namespace opencensus

#endif
